rule all:
    input:
        'resources/a-test-copy'


rule os_agnostic_copier:

    config:
        'copier_config.yaml'
    output:
        'resources/a-test-copy'
    wrapper:
        '../os_agnostic_copier'
