configfile: 'copier_config.yaml'
rule all:
    input:
        'resources/test_dir_A',
        'resources/test_dir_D',
        'resources/test_file_B.txt'


rule os_agnostic_copier:
    output:
        required_dirs = [directory('resources/test_dir_A'),
        directory('resources/test_dir_D')],

        required_files = ['resources/test_file_B.txt']


    wrapper:
        "file:../"