name: os_agnostic_copier
description:
  os_agnostic_copier allows for the copying of files and directories from a specified network source
  to a destination directory for both windows and linux systems using either robocopy or rsync. 
url: https://gccode.ssc-spc.gc.ca/sustainabilityMetrics/os_agnostic_copier
config: Path to the source and destination configs